networks:
  ${GITHUB_PROJECT}-network:
    internal: true
  volume-init-network:
    internal: false

services:
  simplilearn-phpinfo-service:
    command: 
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    entrypoint: /usr/bin/php
    env_file:
      - ./${ENV_FILE}
    environment:
      HELLO: world
      AUTHOR: Sebastian
    image: ${GITHUB_USERNAME}/${GITHUB_PROJECT}:${GITHUB_RELEASE}
    networks:
      - ${GITHUB_PROJECT}-network
    ports:
      - 80:8080
    user: nobody
    volumes:
      - ${GITHUB_PROJECT}-volume:/shared/:ro
    working_dir: /shared/${GITHUB_PROJECT}/${GITHUB_SRC}/
  volume-init-service:
    command:
      - -c
      - rm -rf ${GITHUB_PROJECT}/ && git clone https://github.com/${GITHUB_USERNAME}/${GITHUB_PROJECT} && cd ${GITHUB_PROJECT}/ && git checkout 2021-08 && sleep 1000
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
    entrypoint: /bin/sh
    env_file:
      - ./${ENV_FILE}
    environment:
      HELLO: bye
    image: alpine/git:latest
    networks:
      - volume-init-network
    user: root
    volumes:
      - ${GITHUB_PROJECT}-volume:/shared/:rw
    working_dir: /shared/
  
version: '3.8'

volumes:
  simplilearn-phpinfo-volume:
