apiVersion: v1
kind: ReplicationController
metadata:
  name: simplilearn-phpinfo-rc
spec:
  replicas: 2
  selector:
    simplilearn-phpinfo-key: simplilearn-phpinfo-value
  template:
    metadata:
      labels:
        simplilearn-phpinfo-key: simplilearn-phpinfo-value
    spec:
      containers:
        -
          args:
            - -f
            - index.php
            - -S
            - 0.0.0.0:8080
          command:
            - /usr/bin/php
          env:
            - 
              name: HELLO
              value: world
            - 
              name: AUTHOR
              value: Sebastian
          image: academiaonline/simplilearn-phpinfo:single-line
          name: simplilearn-phpinfo-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 120Mi
            requests:
              cpu: 50m
              memory: 120Mi
          volumeMounts:
            -
              mountPath: /shared/
              name: simplilearn-phpinfo-volume
              readOnly: true
          workingDir: /shared/simplilearn-phpinfo/src/
      initContainers:
        -
          args:
            - -c
            - rm -rf simplilearn-phpinfo/ && git clone https://github.com/academiaonline/simplilearn-phpinfo && cd simplilearn-phpinfo/ && git checkout 2021-08
          command:
            - /bin/sh
          env:
            - 
              name: HELLO
              value: bye
          image: alpine/git:latest
          name: init-container
          resources:
            limits:
              cpu: 50m
              memory: 120Mi
            requests:
              cpu: 50m
              memory: 120Mi
          volumeMounts:
            -
              mountPath: /shared/
              name: simplilearn-phpinfo-volume
              readOnly: false
          workingDir: /shared/
      volumes:
        -
          emptyDir: {}
          name: simplilearn-phpinfo-volume
          
    
    
